# ====================================================================
#                      é»ƒé‡‘æ¨™æº–ç‰ˆçš„ mkdocs.yml
# ====================================================================

# ç¶²ç«™åŸºæœ¬è³‡è¨Š
site_name: Hachi çš„è·¨é ˜åŸŸå­¸ç¿’ç­†è¨˜
site_url: https://hachi.github.io/DCS-learning/ # <-- éƒ¨ç½²åˆ° GitHub æ™‚è«‹å–æ¶ˆè¨»è§£
repo_url: https://github.com/hachi/DCS-learning
repo_name: hachi/DCS-learning
site_author: Hachi Tsai

# ä¸»é¡Œèˆ‡å¤–è§€è¨­å®š
theme:
  font:
    text: Roboto 
  name: material
  language: zh-TW # ç¹é«”ä¸­æ–‡
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.copy
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.tracking
  palette:
    # æ·ºè‰²æ¨¡å¼
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: åˆ‡æ›åˆ°æ·±è‰²æ¨¡å¼
    # æ·±è‰²æ¨¡å¼
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: åˆ‡æ›åˆ°æ·ºè‰²æ¨¡å¼

# Plug-in
plugins:
  - search
  - mermaid2:
      version: 11.5.0
      arguments:
        theme: 'base'
        themeVariables:
          primaryColor: '#FCF3CF'
          primaryTextColor: '#EF6C00'


# å°Žè¦½åˆ—è¨­å®š
nav:
  - ðŸ‘‹ é¦–é ç¸½è¦½: index.md
  - å·¥æ¥­è‡ªå‹•åŒ–:
      - DCSæŽ§åˆ¶ç³»çµ±èˆ‡Mermaid:
          - é‚è¼¯æŽ§åˆ¶åœ–åƒåŒ–: DCS/Hitachi/Control-logic-mermaid.md
          - æŽ§åˆ¶é‚è¼¯ç­†è¨˜: DCS/Hitachi/concepts.md
          - æŠ€è¡“æ—¥æ–‡ç­†è¨˜: DCS/Hitachi/japanese.md
      - PLC æŠ€è¡“:
          - MELSEC-Q æ“ä½œç­†è¨˜: PLC/MELSEC-Q.md
      - HMI æ•™å­¸:
          - iFIX ç­†è¨˜: HMI/iFIX.md
  - å€å¡ŠéˆæŠ€è¡“:
      - æ™ºèƒ½åˆç´„æ‡‰ç”¨: BlockChain/SmartContract.md
  - PROGRAMING:
      - GitHub: Programing/github.md
      - Python with AI-ML: Programing/python-with-aiml.md
      - Docker: Programing/docker.md
  - è³‡æºæ•´ç†:
      - å¸¸ç”¨å·¥æ¥­é€šè¨Šå”å®š: Resources/OT-communicating-protocl.md
      - æŽ¨è–¦å­¸ç¿’è³‡æº: Resources/Coursera/Learning_Schedule.md

# Markdown æ“´å……åŠŸèƒ½
markdown_extensions:
  - abbr
  - attr_list  #å¥½åƒè·ŸCSSæœ‰é—œä¿‚çš„
  - def_list   #åŒä¸Š
  - admonition
  - footnotes 
  - md_in_html           # <--- çµ•å°é—œéµï¼å…è¨±åœ¨ HTML ä¸­è™•ç† Markdown  
  - toc:
      permalink: true
  - tables
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.highlight:
       line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.betterem
  - pymdownx.blocks.caption
  # Mermaid çš„é—œéµè¨­å®š
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


# ç¤¾ç¾¤é€£çµ
extra:
  mermaid: 'false'
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hachi
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/hachi-tsai

